export const data = [
  {
    study_name: "Subject",
    features: [
      {
        name: "User ID",
        summary: [
          { type: "Count", value: "101" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
          { type: "Count", value: "101" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Number",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Age",
        summary: [
          { type: "Count", value: "103" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
          { type: "Count", value: "103" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Fitzpatrick skin type",
        summary: [
          { type: "Count", value: "104" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
          { type: "Count", value: "104" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Height",
        summary: [
          { type: "Count", value: "105" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
          { type: "Count", value: "105" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Weight",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "BMI",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Pet in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Work with animals",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Menopause",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "User ID",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Number",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Age",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Fitzpatrick skin type",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Height",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Weight",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "BMI",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Pet in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Work with animals",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Menopause",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "User ID",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Number",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Age",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Fitzpatrick skin type",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Height",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Weight",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "BMI",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Pet in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Work with animals",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Menopause",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "User ID",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Number",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Age",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Fitzpatrick skin type",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Height",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Weight",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "BMI",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Pet in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Work with animals",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Menopause",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "User ID",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Number",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Age",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Fitzpatrick skin type",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Height",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Weight",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "BMI",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Pet in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Work with animals",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Menopause",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "User ID",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Number",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Age",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Fitzpatrick skin type",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Height",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Weight",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "BMI",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Pet in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Work with animals",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Menopause",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "User ID",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Number",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Age",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Fitzpatrick skin type",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Height",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Weight",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "BMI",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Smoker in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Pet in house",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Work with animals",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
      {
        name: "Menopause",
        summary: [
          { type: "Count", value: "102" },
          { type: "Mean", value: "38.0" },
          { type: "Standard deviation", value: "9.2" },
          { type: "Variance", value: "86.0" },
          { type: "25th percentile", value: "31.0" },
          { type: "75th percentile", value: "45.0" },
          { type: "Interquartile", value: "14.0" },
          { type: "Median", value: "38.0" },
          { type: "Mode", value: "27" },
          { type: "Skewness", value: "-0.2" },
          { type: "Kurtosis", value: "-0.8" },
        ],
      },
    ],
  },
];

// "User ID",
// "Number",
// "Age",
// "Fitzpatrick skin type",
// "Height",
// "Weight",
// "BMI",
// "Smoker",
// "Smoker in house",
// "Pet in house",
// "Work with animals",
// "Menopause",
